### ISSUE TITLE
DLib is manually installed to /usr/local/lib ...

### ISSUE THREAD

**Issue by jiapei100** [ETH3D/badslam#26]
Hi, I actually have manually installed **DLib** to _/usr/local/lib_, how should I define **DLib_DIR** ? 

I don't have 
**DLibConfig.cmake
dlib-config.cmake**
but with the following **dlib.pc**

```
% cat /usr/local/lib/pkgconfig/dlib.pc 
libdir=/usr/local/lib
includedir=/usr/local/include

Name: dlib
Description: Numerical and networking C++ library
Version: 19.17.0
Libs: -L${libdir} -ldlib
Cflags: -I${includedir}
Requires: libpng
```

The current **ERROR** is:

```
 CMake Error at applications/badslam/CMakeLists.txt:7 (find_package):
   By not providing "FindDLib.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "DLib", but
   CMake did not find one.

   Could not find a package configuration file provided by "DLib" with any of
   the following names:

     DLibConfig.cmake
     dlib-config.cmake

   Add the installation prefix of "DLib" to CMAKE_PREFIX_PATH or set
   "DLib_DIR" to a directory containing one of the above files.  If "DLib"
   provides a separate development package or SDK, be sure it has been
   installed.

```

Can anybody help to fix this issue?

Thank you 
Pei

**Comment by puzzlepaint** [comment]
Hi, does */usr/local/include/DLib/* contain a file **DLibConfig.cmake**? If yes, you could set **DLib_DIR** to this directory. Otherwise, it would be a possibility to write a custom **DLibConfig.cmake** that points to your installation directories. As an example, here is the content of */usr/local/include/DLib/DLibConfig.cmake* on my system:

```cmake
FIND_LIBRARY(DLib_LIBRARY DLib
    PATHS "/usr/local/lib"
)
FIND_PATH(DLib_INCLUDE_DIR DLibConfig.cmake
    PATHS "/usr/local/include/DLib" 
)
LIST(APPEND DLib_INCLUDE_DIR
  ${DLib_INCLUDE_DIR}/../ ${DLib_INCLUDE_DIR}/../DUtils
  ${DLib_INCLUDE_DIR}/../DUtilsCV ${DLib_INCLUDE_DIR}/../DVision)
SET(DLib_LIBRARIES ${DLib_LIBRARY})
SET(DLib_LIBS ${DLib_LIBRARY})
SET(DLib_INCLUDE_DIRS ${DLib_INCLUDE_DIR})
```

**Comment by brookman** [comment]
@jiapei100 You have probably installed the wrong library. There are two unrelated libraries which have the same name (but different capitalization in the name):
- [dlib.net](http://dlib.net/) (the wrong one)
- [DLib](https://github.com/dorian3d/DLib] (the right one)

I made the same mistake and lost a few hours because of it. ^^'

**Comment by puzzlepaint** [comment]
Indeed, the .pc file referenced above contains `Description: Numerical and networking C++ library`, which I overlooked when I first replied. I just added a warning about this to the Readme to hopefully prevent this from happening to more people.

**Comment by jiapei100** [comment]
@brookman 

Thank you @brookman . There are still compatibility issue:

https://github.com/dorian3d/DLib/issues/23
